apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-launcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-launcher-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-launcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-launcher-role
subjects:
- kind: ServiceAccount
  name: pod-launcher
