apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ index .Values "flow" "flow-id" }}
spec:
  type: ClusterIP
  ports:
    - port: 7860
      targetPort: 7860
  selector:
    app: langflow-runtime
