flow:
  replicaCount: 1
  flow-id: 'your-flow-id'
  service:
    port: 7860
  image:
    repository: langflowai/langflow
    tag: latest
    pullPolicy: IfNotPresent
  downloadFlows:
    path: /app/flows
  backend:
    backend:
    externalDatabase:
      enabled: true
      host: kitchen-umbrella-postgres
      driver: postgresql
      port: "5432"
      user: shareduser
      password: sharedpass
      database: langflow_prd
    sqlite:
      enabled: false


